### ISSUE TITLE
[Feature Request] Status information

### ISSUE THREAD

**Issue by ShagoY** [natekspencer/hacs-litterrobot#8]
hello :)

First of all thank you for your work!

I have a small question, why don't you use the "status" information in the widget "vacuum.lilas_litter_box"?

I find that there is much more information there, for example it indicates when the cat is doing things (Cat Sensor Timing).

![image](https://user-images.githubusercontent.com/25367500/109391264-72f78e80-7916-11eb-9cde-c7db21803a6e.png)

So I created a sensor but I admit that I would like it to be displayed directly... Instead of "On the base" in my screenshot.

```
# Litter Robot
- platform: template
  sensors:
    lilas_status:
      friendly_name_template: "{{ state_attr('vacuum.lilas_litter_box','friendly_name') }} Status"
      value_template: "{{ state_attr('vacuum.lilas_litter_box','status') }}"
```
What do you think about it ?

**Comment by natekspencer** [comment]
I don't disagree with you. The status definitely shows more information. That being said, there are a couple of reasons why I didn't do this:
1. HA only officially supports a certain set of "vacuum" states: https://developers.home-assistant.io/docs/core/entity/vacuum/#states
    - Using unsupported states, while possible, risks potentially having this component break or be blocked by HA should the inherited `VacuumEntity` code be changed/restricted.
2. The default entity display for a vacuum is sorely lacking. I wish there was a vacuum card, similar to how a thermostat card is available.
    - I actually use a custom lovelace card for my LR unit, which includes the ability to show the status: https://github.com/denysdovhan/vacuum-card
    - This is an example of my configuration for it:
```yaml
type: 'custom:vacuum-card'
entity: vacuum.shit_be_gone_litter_box
image: 'https://brands.home-assistant.io/litterrobot/icon@2x.png'
compact_view: false
show_name: true
show_status: true
show_toolbar: true
stats:
  default:
    - entity_id: switch.shit_be_gone_sleep_mode
      subtitle: Sleep Mode
    - attribute: clean_cycle_wait_time_minutes
      unit: minutes
      subtitle: Clean Cycle Wait Time
    - attribute: power_status
      subtitle: Power Status
actions:
  - name: Reset Waste Drawer
    service: vacuum.send_command
    icon: 'mdi:delete-variant'
    service_data:
      entity_id: vacuum.shit_be_gone_litter_box
      command: reset_waste_drawer
```
![image](https://user-images.githubusercontent.com/3792831/109397929-ade9ca00-78f6-11eb-871a-18bdbfaecb80.png)
